### ISSUE TITLE
디자인 시스템은 MaterialTheme를 가져가나요?

### ISSUE THREAD

**Issue by snack655** [Team-ComIT/SimTong-Android#88]
https://github.com/Team-ComIT/SimTong-Android/blob/48293d51264908cc2f1ece572bf42c8c2f93880d/core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt#L5

앞으로도 MaterialTheme에 추가적인 값을 붙여나가는 방식으로 진행하는 것인가요?

**Comment by limsaehyun** [comment]
@snack655 디자인 시스템은 재설계 예정입니다. 추후에 디자인 시스템팀에서 결정될 내용으로 보입니다.
